export const POLICY = Object.freeze({
  schemaVersion: "finly_policy.v1",
  paperHost: "https://paper-api.alpaca.markets",
  alpacaMcpVersion: "2.2.1",
  placeOptionOrderSchemaSha256: "sha256:652e116dd021d05fceb7f34b0dcf17d6c3a0dfe82dc47f67372dbf872a521a55",
  underlyings: ["SPY"],
  allowedActions: ["BULL_CALL_DEBIT_SPREAD", "BEAR_PUT_DEBIT_SPREAD", "NO_TRADE"],
  entryDte: { min: 3, max: 14 },
  quoteMaxAgeSeconds: { indicative: 90, opra: 30 },
  maxRelativeLegSpread: 0.25,
  minOpenInterest: 50,
  directionThreshold: 0.18,
  minCoverage: 0.35,
  minAgreement: 0.55,
  minimumProbabilityOfProfit: 0.53,
  minimumRewardRisk: 1.25,
  minimumEvDollars: 10,
  minimumEvToMaxLoss: 0.06,
  riskPerTradeFraction: 0.005,
  halfRiskFraction: 0.0025,
  riskPerTradeDollarCap: 500,
  aggregateRiskFraction: 0.03,
  maxContracts: 4,
  certificateTtlSeconds: 30,
  preflightMaxAgeSeconds: 15,
  entryDebitDriftDollars: 0.10,
  maxUnderlyingDriftFraction: 0.005,
  minimumOptionsLevel: 3,
  minimumPostTradeBuyingPowerFraction: 0.25,
  perturbationCount: 32,
  scenarioPathCount: 2048,
  bootstrapBlockSessions: 5,
  slippagePerLegDollars: 0.03,
  exitSlippagePerLegDollars: 0.03,
  profitTargetMaxGainFraction: 0.3,
  stopLossRemainingDebitFraction: 0.5,
  expiryGuardDte: 2,
  interestRate: 0.04,
  dividendYield: 0.012,
});

// Live alpha calibration is execution-scope-specific. It does not modify the
// frozen research POLICY above or any historical/public replay receipt.
export const LIVE_ALPHA_CONFIDENCE_POLICY = Object.freeze({
  directionThreshold: 0.12,
  minCoverage: 0.30,
  minAgreement: 0.45,
  minimumProbabilityOfProfit: 0.45,
  minimumRewardRisk: 1.25,
  minimumEvDollars: 5,
  minimumEvToMaxLoss: 0.02,
  sourceRemovalMinimumPassRate: 1,
  perturbationMaximumDirectionFlips: 0,
  perturbationMinimumNonzeroDirectionRate: 0.75,
  perturbationMinimumTradeRate: 0.50,
  perturbationMinimumSameStructureRate: 0.50,
});

export const LIVE_EXECUTION_SAFETY_POLICY = Object.freeze({
  maximumContracts: 1,
  maximumLossDollars: POLICY.riskPerTradeDollarCap,
  maximumAggregateRiskFraction: POLICY.aggregateRiskFraction,
  minimumOptionsLevel: POLICY.minimumOptionsLevel,
});

export const FAMILY_BASE_WEIGHTS = Object.freeze({
  market: 0.5,
  options: 0.2,
  events: 0.25,
  prediction_market: 0.05,
});
